spring:
  datasource:
    url: ${POSTGRES_DB_JDBC}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: organisation
  data:
    redis:
      host: ${REDIS_DB_HOST}
      port: ${REDIS_DB_PORT}
  application:
    name: guildmaster
server:
  port: 8085
  origins:
    - ${ORIGIN_API_URL}
  connections:
    colovia: ${COLOVIA_SERVICE_URL},
    secunda: ${SECUNDA_SERVICE_URL},

logging:
  level:
    root: INFO
    com.yoku.guildmaster: DEBUG  # Adjust the logging level for your application packages

  file:
    name: ./logs/application.log  # This will store logs in the root folder under 'logs/application.log'
    # Or use an absolute path, e.g., '/path/to/logs/application.log' if needed

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # Custom console log pattern
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"    # Custom file log pattern

  # Optional: Max file size and number of files to keep for rotation
  logback:
    rolling-policy:
      file-name-pattern: ./logs/application-%d{yyyy-MM-dd}.%i.log  # Rolling logs per day
      max-history: 30  # Keep logs for the last 30 days


